language: node_js

node_js:
  - "6"

sudo: required

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm install -g yarn
  - cd ~/build/petrasphere/gomicro && yarn

script:
  - cd ~/build/petrasphere/gomicro && yarn test
